# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Simple
version:      0.12
version_from: lib/Class/Simple.pm
installdirs:  site
requires:
    Class::ISA:                    0.32
    List::Util:                    0
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
